modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gem_mod"
version="1.0.0"
displayName="Gem mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Casa, MCreator"

[[dependencies.gem_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



